# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestOpenDou():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()
    @pytest.mark.parametrize("input_value", ["qa", "developer", "HR"])
    def test_openDou(self, input_value):
        # Test name: Open Dou
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get("https://dou.ua/")
        # 2 | setWindowSize | 1470x920 |
        self.driver.maximize_window()
        # 3 | click | css=.b-head li:nth-child(6) > a |
        self.driver.find_element(By.CSS_SELECTOR, ".b-head li:nth-child(6) > a").click()
        # 4 | click | name=search |
        self.driver.find_element(By.NAME, "search").click()
        # 5 | type | name=search | qa
        self.driver.find_element(By.NAME, "search").send_keys(input_value)
        # 6 | click | css=.btn-search |
        self.driver.find_element(By.CSS_SELECTOR, ".btn-search").click()
        assert self.driver.find_element(By.CLASS_NAME, "b-inner-page-header")


